# Generated by Django 4.2.7 on 2025-05-08 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0017_remove_psychologistprofile_experience_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pricing", "0003_alter_suggestedprice_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suggestedprice",
            options={},
        ),
        migrations.AddField(
            model_name="suggestedprice",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="suggestedprice",
            name="psychologist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.psychologistprofile",
            ),
        ),
        migrations.AlterModelTable(
            name="suggestedprice",
            table=None,
        ),
    ]
