# Generated by Django 4.2.7 on 2025-05-08 19:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0017_remove_psychologistprofile_experience_description_and_more"),
        ("appointments", "0005_alter_appointment_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="Contenido del comentario")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Calificación del 1 al 5",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "La calificación mínima es 1"
                            ),
                            django.core.validators.MaxValueValidator(
                                5, "La calificación máxima es 5"
                            ),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de creación del comentario",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el comentario ha sido aprobado por un administrador",
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        help_text="Cita a la que se refiere el comentario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Paciente que hace el comentario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="profiles.clientprofile",
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        help_text="Psicólogo que recibe el comentario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="profiles.psychologistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
                "ordering": ["-created_at"],
            },
        ),
    ]
