# Generated by Django 4.2.7 on 2025-05-23 05:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0017_remove_psychologistprofile_experience_description_and_more"),
        ("appointments", "0005_alter_appointment_created_at_and_more"),
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Valoración",
                "verbose_name_plural": "Valoraciones",
            },
        ),
        migrations.RemoveField(
            model_name="comment",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="text",
        ),
        migrations.AddField(
            model_name="comment",
            name="comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comentario o descripción de la valoración",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("APPROVED", "Aprobado"),
                    ("REJECTED", "Rechazado"),
                ],
                default="PENDING",
                help_text="Estado de la valoración",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="appointments.appointment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Fecha y hora de creación de la valoración"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_reviews",
                to="profiles.clientprofile",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="psychologist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_reviews",
                to="profiles.psychologistprofile",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(
                help_text="Calificación del 1 al 5",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="La calificación mínima es 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        5, message="La calificación máxima es 5"
                    ),
                ],
            ),
        ),
    ]
